"""
Script2API — Core conversion engine.

Takes raw Python source code and wraps every top-level function
in a FastAPI route, returning a runnable router module as a string.
"""
import ast
import textwrap
from dataclasses import dataclass, field

@dataclass
class FunctionInfo:
    name: str
    args: list[str] = field(default_factory=list)
    docstring: str = ""
    return_hint: str = "Any"

def extract_functions(source: str) -> list[FunctionInfo]:
    """Parse source and return metadata about each top-level function."""
    tree = ast.parse(source)
    functions = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if node.col_offset != 0:          # skip nested / class methods
            continue
        if node.name.startswith("_"):     # skip private helpers
            continue
        args = [a.arg for a in node.args.args if a.arg != "self"]
        doc = ast.get_docstring(node) or ""
        functions.append(FunctionInfo(name=node.name, args=args, docstring=doc))
    return functions

def build_router_source(user_source: str, module_name: str = "user_script") -> str:
    """Generate a FastAPI router that wraps each function as a POST endpoint."""
    functions = extract_functions(user_source)
    if not functions:
        return ""

    lines = [
        "# AUTO-GENERATED by Script2API — do not edit manually",
        "from typing import Any, Optional",
        "from fastapi import APIRouter",
        "from pydantic import BaseModel",
        "",
        f"router = APIRouter(prefix='/{module_name}', tags=['{module_name}'])",
        "",
        "# ---- injected user code ----",
    ]

    # Indent & inject user source safely
    lines += textwrap.indent(user_source, "").splitlines()
    lines.append("")

    for fn in functions:
        model_name = f"_{fn.name.capitalize()}Input"
        field_lines = [f"    {arg}: Any = None" for arg in fn.args]
        model_body = field_lines if field_lines else ["    pass"]
        lines += [f"class {model_name}(BaseModel):"] + model_body
        lines += [
            "",
            f'@router.post("/{fn.name}")',
            f"def endpoint_{fn.name}(body: {model_name}):",
            f'    """{fn.docstring or fn.name}"""',
            f"    result = {fn.name}(**{{k: v for k, v in body.model_dump().items() if v is not None}})",
            '    return {"result": result}',
            "",
        ]

    return "\n".join(lines)

def convert(source: str, script_name: str = "script") -> dict:
    """
    Full pipeline: validate → extract → generate.
    Returns a dict with generated_code, endpoints, warnings.
    """
    # Validate syntax
    try:
        ast.parse(source)
    except SyntaxError as e:
        return {"success": False, "error": f"SyntaxError: {e}"}

    functions = extract_functions(source)
    router_code = build_router_source(source, module_name=script_name)

    endpoints = [
        {"path": f"/{script_name}/{fn.name}", "method": "POST", "args": fn.args, "description": fn.docstring}
        for fn in functions
    ]

    warnings = []
    if not functions:
        warnings.append("No public top-level functions found. Nothing was converted.")

    return {
        "success": True,
        "script_name": script_name,
        "endpoints": endpoints,
        "generated_code": router_code,
        "warnings": warnings,
    }
